---
- name: Install Apache Web Server on RHEL 10
  hosts: webservers
  become: true

  tasks:
    - name: Ensure package manager cache is updated
      dnf:
        update_cache: yes

    - name: Install GPG key for Red Hat packages
      rpm_key:
        state: present
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

    - name: Install httpd
      dnf:
        name: httpd
        state: present
        validate_certs: yes
