---
- name: Check Uptime on Webservers
  hosts: webservers
  gather_facts: false
  become: false

  tasks:
    - name: Get uptime of the server
      command: uptime
      register: uptime_result

    - name: Show uptime
      debug:
        msg: "{{ inventory_hostname }} uptime: {{ uptime_result.stdout }}"
