---
- name: Install Apache Web Server on RHEL 10
  hosts: webservers
  become: true

  tasks:
    - name: Ensure package manager cache is up-to-date
      dnf:
        update_cache: yes

    - name: Import Red Hat GPG key
      rpm_key:
        state: present
        key: /etc/pki/rpm-gpg/RPM-GPG-KEY-redhat-release

    - name: Install httpd package
      dnf:
        name: httpd
        state: present

    - name: Start and enable httpd
      service:
        name: httpd
        state: started
        enabled: true
