---
- name: Copy data folder to remote hosts
  hosts: all
  become: yes

  tasks:
    - name: Copy data folder to /tmp on remote
      copy:
        src: data/        # relative path inside files/
        dest: /tmp/data/  # destination path on remote
        mode: '0755'
