---
- name: Copy file to remote server
  hosts: all
  become: yes

  tasks:
    - name: Copy file from local to remote
      copy:
        src: /data/
        dest: /tmp/
        owner: root
        group: root
        mode: '0644'
